FROM osmsplitter:latest
MAINTAINER James Michael DuPont <h4ck3rm1k3@thefr33.com>
VOLUME /var/lib/splitter/
RUN mkdir -p /var/lib/splitter/north-america/us/kansas 

# to download this:
#RUN cd /var/lib/splitter/north-america/us/kansas  && wget http://download.geofabrik.de/north-america/us/kansas-latest.osm.pbf

## to insert a copy 
add kansas-latest.osm.pbf /var/lib/splitter/north-america/us/kansas



